# Generated by Django 6.0.6 on 2026-06-28 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('ticket_type', models.CharField(choices=[('regular', 'Regular Ticket - ₦20,000'), ('vip', 'VIP Ticket - ₦100,000')], default='regular', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='tickets/qr/')),
            ],
        ),
    ]
