# Generated by Django 6.0.6 on 2026-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ticket_type',
            field=models.CharField(choices=[('ticket', 'Ticket - ₦35,000'), ('vendor', 'Vendorship Participation - ₦250,000')], default='ticket', max_length=20),
        ),
    ]
