# Generated by Django 6.0.6 on 2026-07-10 22:25

import django.db.models.deletion
import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_registration_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(choices=[('owner', 'Owner'), ('mandate', 'Mandate'), ('developer', 'Developer')], max_length=20)),
                ('company_name', models.CharField(max_length=200, verbose_name='Company / Owner / Developer Name')),
                ('property_type', models.CharField(max_length=200, verbose_name='Type of Property')),
                ('location', models.CharField(max_length=300, verbose_name='Property Location')),
                ('title', models.CharField(help_text='e.g. C of O, R of O, Deed of Assignment', max_length=200, verbose_name='Title / Document Type')),
                ('open_market_price', models.CharField(max_length=100, verbose_name='Open Market Price')),
                ('event_only_price', models.CharField(max_length=100, verbose_name='Event Only Price')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_application', to='events.registration')),
            ],
        ),
        migrations.CreateModel(
            name='VendorMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=events.models.vendor_media_path)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='events.vendorapplication')),
            ],
        ),
    ]
